### PR TITLE
Fix continue round when latest frame does not exist

### LINKED ISSUE #133: Fix Experiment API resume "continue round" when latest frame does not exist
I noticed if the experiment config resume mode is "continue round" and the latest frame does not exist we still continue the round. But it probably makes more sense to reset the round since we have no position to move the player back to.

### PR DESCRIPTION
**Pull request by danielholmes839**
closes #133
- see the issue for description
- updated the state diagram in the docs folder

### CODE REVIEW

File: vsn-backend/features/experiment/active_experiment.go [hunk 1]
```diff
@@ -96,7 +96,7 @@ func (ae *activeExperiment) Resume() {
 	}
 
 	// resume and continue round
-	if ae.Config.Resume == model.CONTINUE_ROUND {
+	if ae.Config.Resume == model.CONTINUE_ROUND && ae.LatestFrame != nil {
```
Comment (danielholmes839) [inline vsn-backend/features/experiment/active_experiment.go:99]: This is the fix

**Review by FarinaSalman — APPROVED** [review]
